name: Icon Request
description: Request a new icon to be added to the set.
title: "[Icon] Add ai-"
labels: [icon, external]
assignees:
  - studio384
body:
  - type: input
    id: name
    attributes:
      label: Description
      description: Describe the icon you want to see added.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: How would it be used?
      description: Describe under what situations this icon would be useful.
      value:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example icon
      description: Add an image below as an example for a similar icon if you have any.
      value:
      render: markdown

  - type: checkboxes
    id: checklist
    attributes:
      label: Check all that apply.
      options:
        - label: This is a single icon or part of an expected pair (e.g. `eye` and `eye-slashed`).
          required: true
        - label: There are no priorly made issues with the same request.
          required: true
        - label: An example image is included if available. (optional)
          required: false