/* 🤖 this file was generated by svg-to-ts*/
export const aiAlarm: {
  name: 'alarm';
  data: string;
} = {
  name: 'alarm',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.23 1.34a7.52 7.52 0 014.93 4.93 3.5 3.5 0 00-4.93-4.93zm-4.46 0a7.52 7.52 0 00-4.93 4.93 3.5 3.5 0 014.93-4.93zM9.25 8.5V5.75a.75.75 0 011.5 0v2.44l.91.91a.75.75 0 11-1.06 1.06L9.53 9.1a.76.76 0 01-.03-.03.75.75 0 01-.25-.56z"/><path fill-rule="evenodd" d="M10 15c1.35 0 2.6-.4 3.63-1.1l1.31 1.52a.75.75 0 001.14-.98l-1.3-1.53A6.5 6.5 0 1010 15zm0-1.5a5 5 0 110-10 5 5 0 010 10z"/><path d="M6.37 13.9c-.42-.29-.8-.62-1.14-.99l-1.31 1.53a.75.75 0 101.14.98l1.3-1.53z"/></svg>`
};
export const aiAngleDown: {
  name: 'angle_down';
  data: string;
} = {
  name: 'angle_down',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 6.56A.75.75 0 115.56 5.5l4.26 4.26c.1.1.26.1.36 0l4.26-4.26a.75.75 0 011.06 1.06l-4.8 4.8a1 1 0 01-1.4 0l-4.8-4.8z"/></svg>`
};
export const aiAngleLeft: {
  name: 'angle_left';
  data: string;
} = {
  name: 'angle_left',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.47 2.53a.75.75 0 111.06 1.06L8.27 7.85c-.1.1-.1.26 0 .36l4.26 4.26a.75.75 0 11-1.06 1.06l-4.8-4.8a1 1 0 010-1.4l4.8-4.8z"/></svg>`
};
export const aiAngleRight: {
  name: 'angle_right';
  data: string;
} = {
  name: 'angle_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8.53 13.53a.75.75 0 01-1.06-1.06l4.26-4.26c.1-.1.1-.26 0-.36L7.47 3.6a.75.75 0 111.06-1.06l4.8 4.8a1 1 0 010 1.4l-4.8 4.8z"/></svg>`
};
export const aiAngleUp: {
  name: 'angle_up';
  data: string;
} = {
  name: 'angle_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.5 9.5a.75.75 0 01-1.06 1.06L10.18 6.3a.25.25 0 00-.36 0l-4.26 4.26A.75.75 0 114.5 9.5l4.8-4.8a1 1 0 011.4 0l4.8 4.8z"/></svg>`
};
export const aiArrowDownToLine: {
  name: 'arrow_down_to_line';
  data: string;
} = {
  name: 'arrow_down_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 1.75l-.03 7.97-3.19-3.19a.75.75 0 00-1.06 1.06l4.3 4.3a1 1 0 001.4 0l4.3-4.3a.75.75 0 10-1.06-1.06l-3.19 3.19.03-7.97a.75.75 0 00-1.5 0zM4.75 13.5a.75.75 0 000 1.5h10.5a.75.75 0 000-1.5H4.75z"/></svg>`
};
export const aiArrowDown: {
  name: 'arrow_down';
  data: string;
} = {
  name: 'arrow_down',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 12.19V1.75a.75.75 0 111.5 0v10.44l3.69-3.69a.75.75 0 011.06 1.06l-4.8 4.8a1 1 0 01-1.4 0l-4.8-4.8A.75.75 0 115.56 8.5l3.69 3.69z"/></svg>`
};
export const aiArrowLeftFromBracket: {
  name: 'arrow_left_from_bracket';
  data: string;
} = {
  name: 'arrow_left_from_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M12 14.25c0 .41.34.75.75.75H15a3 3 0 003-3V4a3 3 0 00-3-3h-2.25a.75.75 0 000 1.5H15c.83 0 1.5.67 1.5 1.5v8c0 .83-.67 1.5-1.5 1.5h-2.25a.75.75 0 00-.75.75z"/><path fill-rule="evenodd" d="M7.2 12.5c-.3.3-.77.3-1.06 0l-3.8-3.8a1 1 0 010-1.4l3.8-3.8A.75.75 0 017.2 4.56L4.51 7.25h7.44a.75.75 0 010 1.5H4.51l2.69 2.69c.3.3.3.77 0 1.06z"/></svg>`
};
export const aiArrowLeftToBracket: {
  name: 'arrow_left_to_bracket';
  data: string;
} = {
  name: 'arrow_left_to_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 1.75A.75.75 0 007.25 1H5a3 3 0 00-3 3v8a3 3 0 003 3h2.25a.75.75 0 000-1.5H5A1.5 1.5 0 013.5 12V4c0-.83.67-1.5 1.5-1.5h2.25c.41 0 .75-.34.75-.75z"/><path fill-rule="evenodd" d="M12.5 12.5c-.3.3-.77.3-1.06 0l-3.8-3.8a1 1 0 010-1.4l3.8-3.8a.75.75 0 011.06 1.06L9.81 7.25h7.44a.75.75 0 010 1.5H9.81l2.69 2.69c.3.3.3.77 0 1.06z"/></svg>`
};
export const aiArrowLeftToLine: {
  name: 'arrow_left_to_line';
  data: string;
} = {
  name: 'arrow_left_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 2.75a.75.75 0 00-1.5 0v10.5a.75.75 0 001.5 0V2.75zm11.75 4.5l-7.97-.03 3.19-3.19a.75.75 0 10-1.06-1.06l-4.3 4.3a1 1 0 000 1.4l4.3 4.3a.75.75 0 001.06-1.06L8.28 8.72l7.97.03a.75.75 0 000-1.5z"/></svg>`
};
export const aiArrowLeft: {
  name: 'arrow_left';
  data: string;
} = {
  name: 'arrow_left',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M5.84 7.28h10.44a.75.75 0 010 1.5H5.84l3.69 3.69a.75.75 0 11-1.06 1.06l-4.8-4.8a1 1 0 010-1.4l4.8-4.8a.75.75 0 111.06 1.06L5.84 7.28z"/></svg>`
};
export const aiArrowRightFromBracket: {
  name: 'arrow_right_from_bracket';
  data: string;
} = {
  name: 'arrow_right_from_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 1.75A.75.75 0 007.25 1H5a3 3 0 00-3 3v8a3 3 0 003 3h2.25a.75.75 0 000-1.5H5A1.5 1.5 0 013.5 12V4c0-.83.67-1.5 1.5-1.5h2.25c.41 0 .75-.34.75-.75z"/><path fill-rule="evenodd" d="M12.8 3.5c.3-.3.77-.3 1.06 0l3.8 3.8a1 1 0 010 1.4l-3.8 3.8a.75.75 0 11-1.06-1.06l2.69-2.69H8.05a.75.75 0 110-1.5h7.44L12.8 4.56a.75.75 0 010-1.06z"/></svg>`
};
export const aiArrowRightToBracket: {
  name: 'arrow_right_to_bracket';
  data: string;
} = {
  name: 'arrow_right_to_bracket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.75 15a.75.75 0 010-1.5H15c.83 0 1.5-.67 1.5-1.5V4c0-.83-.67-1.5-1.5-1.5h-2.25a.75.75 0 010-1.5H15a3 3 0 013 3v8a3 3 0 01-3 3h-2.25z"/><path d="M8.56 3.5A.75.75 0 007.5 4.56l2.69 2.69H2.75a.75.75 0 000 1.5h7.44L7.5 11.44a.75.75 0 001.06 1.06l3.8-3.8a1 1 0 000-1.4l-3.8-3.8z"/></svg>`
};
export const aiArrowRightToLine: {
  name: 'arrow_right_to_line';
  data: string;
} = {
  name: 'arrow_right_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.5 13.25a.75.75 0 001.5 0V2.75a.75.75 0 00-1.5 0v10.5zM3.75 8.75l7.97.03-3.19 3.19a.75.75 0 101.06 1.06l4.3-4.3a1 1 0 000-1.4l-4.3-4.3a.75.75 0 00-1.06 1.06l3.19 3.19-7.97-.03a.75.75 0 100 1.5z"/></svg>`
};
export const aiArrowRight: {
  name: 'arrow_right';
  data: string;
} = {
  name: 'arrow_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14.16 8.78H3.72a.75.75 0 110-1.5h10.44l-3.69-3.69a.75.75 0 011.06-1.06l4.8 4.8a1 1 0 010 1.4l-4.8 4.8a.75.75 0 11-1.06-1.06l3.69-3.69z"/></svg>`
};
export const aiArrowUpToLine: {
  name: 'arrow_up_to_line';
  data: string;
} = {
  name: 'arrow_up_to_line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M15.25 2.5a.75.75 0 000-1.5H4.75a.75.75 0 000 1.5h10.5zm-4.5 11.75l.03-7.97 3.19 3.19a.75.75 0 101.06-1.06l-4.3-4.3a1 1 0 00-1.4 0l-4.3 4.3a.75.75 0 001.06 1.06l3.19-3.19-.03 7.97a.75.75 0 001.5 0z"/></svg>`
};
export const aiArrowUp: {
  name: 'arrow_up';
  data: string;
} = {
  name: 'arrow_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10.75 3.87v10.44a.75.75 0 01-1.5 0V3.87l-3.69 3.7A.75.75 0 014.5 6.5l4.8-4.8a1 1 0 011.4 0l4.8 4.8a.75.75 0 11-1.06 1.06l-3.69-3.69z"/></svg>`
};
export const aiAzure: {
  name: 'azure';
  data: string;
} = {
  name: 'azure',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.77.67A1 1 0 017.7 0h4.58a1 1 0 01.94.67l4.81 14A1 1 0 0117.1 16h-5.21a1 1 0 01-.68-.26L8.46 13.2l-.73 2.12a1 1 0 01-.94.67H2.9a1 1 0 01-.94-1.33l4.8-14zM9.2 6.42L7.89 2.58a.1.1 0 00-.2 0L3.73 14.17c-.06.16.06.33.23.33h2.3c.1 0 .2-.07.24-.17l.76-2.22-.8-.74a.5.5 0 01.34-.87h3.82L10 8.73l-.6 1.77H7.8l1.4-4.08zm4.3 7.91c.04.1.13.17.24.17h2.3c.17 0 .29-.17.23-.33l-4.3-12.5a.25.25 0 00-.23-.17h-2.3a.25.25 0 00-.23.33l4.3 12.5zM9.36 12l2.29 2.1c.08.07.2 0 .16-.1l-.69-2H9.37z"/></svg>`
};
export const aiBackward: {
  name: 'backward';
  data: string;
} = {
  name: 'backward',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8.63 14.28a1 1 0 001.62-.78V2.54a1 1 0 00-1.62-.78L2.02 7.04c-.63.5-.63 1.45 0 1.95l6.6 5.29zM3.2 8.02l5.55-4.44v8.88L3.2 8.02z"/><path d="M15.63 14.28l-3.88-3.1V9.26l4 3.2V3.58l-4 3.2V4.86l3.88-3.1a1 1 0 011.62.78V13.5a1 1 0 01-1.62.78z"/></svg>`
};
export const aiBarsStaggered: {
  name: 'bars_staggered';
  data: string;
} = {
  name: 'bars_staggered',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2 2.75c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H2.75A.75.75 0 012 2.75zM4 8c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H4.75A.75.75 0 014 8zm12 5.25a.75.75 0 00-.75-.75H2.75a.75.75 0 000 1.5h12.5c.41 0 .75-.34.75-.75z"/></svg>`
};
export const aiBars: {
  name: 'bars';
  data: string;
} = {
  name: 'bars',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M3 2.75c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H3.75A.75.75 0 013 2.75zM3 8c0-.41.34-.75.75-.75h12.5a.75.75 0 010 1.5H3.75A.75.75 0 013 8zm.75 4.5a.75.75 0 000 1.5h12.5a.75.75 0 000-1.5H3.75z"/></svg>`
};
export const aiBel: {
  name: 'bel';
  data: string;
} = {
  name: 'bel',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3.72 13.5a1 1 0 01-.87-1.5l.5-.85A5 5 0 004 8.67V6a6 6 0 1112 0v2.67a5 5 0 00.66 2.48l.49.85a1 1 0 01-.87 1.5H12.5a2.5 2.5 0 01-5 0H3.72zm5.28 0a1 1 0 102 0H9zm6.36-1.6a6.5 6.5 0 01-.86-3.23V6a4.5 4.5 0 10-9 0v2.67a6.5 6.5 0 01-.86 3.23l-.06.1h10.84l-.06-.1z"/></svg>`
};
export const aiBox: {
  name: 'box';
  data: string;
} = {
  name: 'box',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13.17 16a2 2 0 001.42-.59l2.82-2.82a2 2 0 00.59-1.42V2a2 2 0 00-2-2H6.83A2 2 0 005.4.59L2.6 3.4A2 2 0 002 4.83V14c0 1.1.9 2 2 2h9.17zM11.5 5.5a1 1 0 011 1v7a1 1 0 01-1 1h-7a1 1 0 01-1-1v-7a1 1 0 011-1h7zm.56-4h2.84c.22 0 .33.27.17.43l-1.92 1.92a.5.5 0 01-.36.15H9.56l2.5-2.5zM7.44 4H4.72a.25.25 0 01-.17-.43l1.92-1.92a.5.5 0 01.36-.15h3.1L7.44 4zM14 5.33a.5.5 0 01.15-.36l1.92-1.92a.25.25 0 01.43.17v7.95a.5.5 0 01-.15.36l-1.92 1.92a.25.25 0 01-.43-.17V5.33z"/></svg>`
};
export const aiBranchUp: {
  name: 'branch_up';
  data: string;
} = {
  name: 'branch_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.25 4.89a2.5 2.5 0 10-1.5 0v6.22a2.5 2.5 0 102.92 1.16 2.28 2.28 0 01-.62-.73 2.5 2.5 0 00-.8-.43V9.25c0-.28.22-.5.5-.5h.82l1.5-1.5H6.75a.5.5 0 01-.5-.5V4.89zM6.5 2.5a1 1 0 11-2 0 1 1 0 012 0zm-1 12a1 1 0 110-2 1 1 0 010 2zm9.75-9.61v1.68l-.98-.98a2.5 2.5 0 00-.52-.4v-.3a2.5 2.5 0 111.5 0zM14.5 3.5a1 1 0 100-2 1 1 0 000 2z"/><path d="M13.2 6.65a1 1 0 00-1.4 0L8.5 9.94A.75.75 0 109.56 11l2.19-2.19v6.44a.75.75 0 001.5 0V8.81L15.44 11a.75.75 0 001.06-1.06l-3.3-3.3z"/></svg>`
};
export const aiBranch: {
  name: 'branch';
  data: string;
} = {
  name: 'branch',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.25 4.89a2.5 2.5 0 10-1.5 0v6.22a2.5 2.5 0 101.5 0V9.25c0-.28.22-.5.5-.5h6.5a2 2 0 002-2V4.89a2.5 2.5 0 10-1.5 0v1.36a1 1 0 01-1 1h-6a.5.5 0 01-.5-.5V4.89zM6.5 2.5a1 1 0 11-2 0 1 1 0 012 0zm-1 12a1 1 0 110-2 1 1 0 010 2zm9-11a1 1 0 110-2 1 1 0 010 2z"/></svg>`
};
export const aiBuilding: {
  name: 'building';
  data: string;
} = {
  name: 'building',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M5.5 2.75c0-.69.56-1.25 1.25-1.25h6.5c.69 0 1.25.56 1.25 1.25V16H16V2.75A2.75 2.75 0 0013.25 0h-6.5A2.75 2.75 0 004 2.75V16h1.5V2.75z"/><path d="M7 4.5v-1c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5zm4-1v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1a.5.5 0 00-.5.5zm-4 5v-1c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5zm4-1v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1a.5.5 0 00-.5.5zM8.5 16v-3.5a1 1 0 011-1h1a1 1 0 011 1V16h-3z"/></svg>`
};
export const aiCalendarAgenda: {
  name: 'calendar_agenda';
  data: string;
} = {
  name: 'calendar_agenda',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 8h-4a.75.75 0 010-1.5h4a.75.75 0 010 1.5zM6 10v1c0 .28.22.5.5.5h7a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-7a.5.5 0 00-.5.5z"/><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const aiCalendarDay: {
  name: 'calendar_day';
  data: string;
} = {
  name: 'calendar_day',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6 8V7c0-.28.22-.5.5-.5h7c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-7A.5.5 0 016 8zm0 2.5v2c0 .28.22.5.5.5h7a.5.5 0 00.5-.5v-2a.5.5 0 00-.5-.5h-7a.5.5 0 00-.5.5z"/><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const aiCalendarHolidays: {
  name: 'calendar_holidays';
  data: string;
} = {
  name: 'calendar_holidays',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.3 9h-.05a.75.75 0 010-1.5h.05a.2.2 0 00.2-.2v-.05a.75.75 0 011.5 0v.05c0 .11.09.2.2.2h.05a.75.75 0 010 1.5h-.05a.2.2 0 00-.2.2v.05a.75.75 0 01-1.5 0V9.2a.2.2 0 00-.2-.2zm-4.55 3h.05c.11 0 .2.09.2.2v.05a.75.75 0 001.5 0v-.05c0-.11.09-.2.2-.2h.05a.75.75 0 000-1.5H8.7a.2.2 0 01-.2-.2v-.05a.75.75 0 00-1.5 0v.05a.2.2 0 01-.2.2h-.05a.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const aiCalendarMonth: {
  name: 'calendar_month';
  data: string;
} = {
  name: 'calendar_month',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6.75 6.5a.75.75 0 110 1.5.75.75 0 010-1.5zm4 .75a.75.75 0 10-1.5 0 .75.75 0 001.5 0zm2.5-.75a.75.75 0 110 1.5.75.75 0 010-1.5zM7.5 9.75a.75.75 0 10-1.5 0 .75.75 0 001.5 0zM10 9a.75.75 0 110 1.5.75.75 0 010-1.5zm4 .75a.75.75 0 10-1.5 0 .75.75 0 001.5 0zM6.75 11.5a.75.75 0 110 1.5.75.75 0 010-1.5zm4 .75a.75.75 0 10-1.5 0 .75.75 0 001.5 0z"/><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const aiCalendarWeek: {
  name: 'calendar_week';
  data: string;
} = {
  name: 'calendar_week',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6 7.25v5a.75.75 0 001.5 0v-5a.75.75 0 00-1.5 0zm3.25 5v-5a.75.75 0 011.5 0v5a.75.75 0 01-1.5 0zm3.25-5v5a.75.75 0 001.5 0v-5a.75.75 0 00-1.5 0z"/><path fill-rule="evenodd" d="M6 .75a.75.75 0 011.5 0V2h5V.75a.75.75 0 011.5 0V2h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V4c0-1.1.9-2 2-2h1V.75zM4.5 14c0 .28.22.5.5.5h10a.5.5 0 00.5-.5V5h-11v9z"/></svg>`
};
export const aiCalendar: {
  name: 'calendar';
  data: string;
} = {
  name: 'calendar',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.75 0A.75.75 0 006 .75V2H5a2 2 0 00-2 2v10c0 1.1.9 2 2 2h10a2 2 0 002-2V4a2 2 0 00-2-2h-1V.75a.75.75 0 00-1.5 0V2h-5V.75A.75.75 0 006.75 0zM4.5 5h11v9a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V5z"/></svg>`
};
export const aiChangeWindowsCan: {
  name: 'change_windows_can';
  data: string;
} = {
  name: 'change_windows_can',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2.11 2.33c0-.5.37-.91.85-.97L9.36.5a.98.98 0 011.12.97V7.5H2.1V2.33zm0 11.32c0 .49.37.9.85.97l3.33.44v-2.73c0-.83.67-1.5 1.5-1.5h2.69V8.48H2.1v5.17zm15.75-5.17v2.74a1.5 1.5 0 00-1.01-.39h-5.4V8.48h6.4zm-5.55-6.14a.98.98 0 00-.85.97V7.5h6.4V2.72a.98.98 0 00-1.12-.98l-4.43.6zm.26 11.8l-.3-.94a1.23 1.23 0 01-.05-.25h-.02c0 .08-.02.16-.04.24l-.3.95h.7z"/><path fill-rule="evenodd" d="M6.78 12.33a1 1 0 011-1h9.08a1 1 0 011 1V15a1 1 0 01-1 1H7.78a1 1 0 01-1-1v-2.67zm3.87 2.82v-.58c-.2.12-.43.18-.68.18a.8.8 0 01-.61-.24.9.9 0 01-.23-.64c0-.29.08-.51.24-.68a.85.85 0 01.64-.24c.24 0 .45.05.64.16v-.6c-.19-.07-.42-.1-.7-.1a1.42 1.42 0 00-1.49 1.5c0 .42.13.76.37 1.01.25.25.59.38 1.02.38.33 0 .6-.05.8-.15zm2.95.1l-1-2.8h-.75l-1.01 2.8h.68l.2-.62h1l.2.62h.68zm2.87 0v-2.8h-.6V14c0 .19 0 .32.02.38h-.01a4.08 4.08 0 00-.14-.23l-1.11-1.7h-.68v2.8h.6v-1.54l-.02-.45.15.23 1.15 1.76h.64z"/></svg>`
};
export const aiChangeWindowsDev: {
  name: 'change_windows_dev';
  data: string;
} = {
  name: 'change_windows_dev',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2.11 2.33c0-.5.37-.91.85-.97L9.36.5a.98.98 0 011.12.97V7.5H2.1V2.33zm0 11.32c0 .49.37.9.85.97l3.33.44v-2.73c0-.83.67-1.5 1.5-1.5h2.69V8.48H2.1v5.17zm15.75-5.17v2.74a1.5 1.5 0 00-1.01-.39h-5.4V8.48h6.4zm-5.55-6.14a.98.98 0 00-.85.97V7.5h6.4V2.72a.98.98 0 00-1.12-.98l-4.43.6zM9.6 12.96v1.78h.31c.28 0 .49-.08.65-.25a.93.93 0 00.23-.67.84.84 0 00-.23-.63.88.88 0 00-.65-.23H9.6z"/><path fill-rule="evenodd" d="M6.78 12.33a1 1 0 011-1h9.08a1 1 0 011 1V15a1 1 0 01-1 1H7.78a1 1 0 01-1-1v-2.67zm2.19 2.92h1c.44 0 .8-.13 1.08-.4.27-.25.4-.6.4-1.04 0-.9-.5-1.36-1.49-1.36h-1v2.8zm4.63 0v-.51h-1.05v-.64h.92v-.51h-.92v-.63h.98v-.51h-1.61v2.8h1.68zm2.8-2.8h-.66l-.58 1.94-.06.29h-.01l-.06-.28-.58-1.95h-.68l.95 2.8h.71l.97-2.8z"/></svg>`
};
export const aiChangeWindows: {
  name: 'change_windows';
  data: string;
} = {
  name: 'change_windows',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2.11 2.33c0-.5.37-.9.86-.97L9.37.5a.99.99 0 011.12.98V7.5H2.1V2.33zm0 11.34c0 .5.37.9.86.97l6.4.85a.99.99 0 001.12-.98V8.5H2.1v5.18zm9.36-10.35a1 1 0 01.86-.98l4.43-.6a.99.99 0 011.12.98v4.79h-6.4V3.3zm0 9.36c0 .5.37.91.86.98l4.43.6a.99.99 0 001.12-.98V8.49h-6.4v4.2z"/></svg>`
};
export const aiCheck: {
  name: 'check';
  data: string;
} = {
  name: 'check',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M16.5 3.5c.3.3.3.77 0 1.06l-7.8 7.8a1 1 0 01-1.4 0l-3.8-3.8A.75.75 0 114.56 7.5L8 10.94l7.44-7.44c.3-.3.77-.3 1.06 0z"/></svg>`
};
export const aiChip: {
  name: 'chip';
  data: string;
} = {
  name: 'chip',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8 5a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V6a1 1 0 00-1-1H8zm.5 1.5h3v3h-3v-3z"/><path fill-rule="evenodd" d="M6 .75V2a2 2 0 00-2 2H2.75a.75.75 0 000 1.5H4v1.75H2.75a.75.75 0 000 1.5H4v1.75H2.75a.75.75 0 000 1.5H4c0 1.1.9 2 2 2v1.25a.75.75 0 001.5 0V14h1.75v1.25a.75.75 0 001.5 0V14h1.75v1.25a.75.75 0 001.5 0V14a2 2 0 002-2h1.25a.75.75 0 000-1.5H16V8.75h1.25a.75.75 0 000-1.5H16V5.5h1.25a.75.75 0 000-1.5H16a2 2 0 00-2-2V.75a.75.75 0 00-1.5 0V2h-1.75V.75a.75.75 0 00-1.5 0V2H7.5V.75a.75.75 0 00-1.5 0zM6 3.5h8c.28 0 .5.22.5.5v8a.5.5 0 01-.5.5H6a.5.5 0 01-.5-.5V4c0-.28.22-.5.5-.5z"/></svg>`
};
export const aiCircleCheck: {
  name: 'circle_check';
  data: string;
} = {
  name: 'circle_check',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.44 5.5L9 8.94 7.56 7.5A.75.75 0 006.5 8.56l1.8 1.8a1 1 0 001.4 0l3.8-3.8a.75.75 0 10-1.06-1.06z"/><path fill-rule="evenodd" d="M18 8A8 8 0 112 8a8 8 0 0116 0zm-1.5 0a6.5 6.5 0 10-13 0 6.5 6.5 0 0013 0z"/></svg>`
};
export const aiCircleInfo: {
  name: 'circle_info';
  data: string;
} = {
  name: 'circle_info',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 4.5a1 1 0 11-2 0 1 1 0 012 0zM11 8v3h.75a.75.75 0 010 1.5h-3a.75.75 0 010-1.5h.75V8.5h-.25a.75.75 0 010-1.5H10a1 1 0 011 1z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const aiCirclePlus: {
  name: 'circle_plus';
  data: string;
} = {
  name: 'circle_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.25 11.25v-2.5h-2.5a.75.75 0 010-1.5h2.5v-2.5a.75.75 0 011.5 0v2.5h2.5a.75.75 0 010 1.5h-2.5v2.5a.75.75 0 01-1.5 0z"/><path fill-rule="evenodd" d="M18 8A8 8 0 112 8a8 8 0 0116 0zm-1.5 0a6.5 6.5 0 10-13 0 6.5 6.5 0 0013 0z"/></svg>`
};
export const aiCircleUser: {
  name: 'circle_user';
  data: string;
} = {
  name: 'circle_user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 9.25a3 3 0 100-6 3 3 0 000 6zm0-1.5a1.5 1.5 0 110-3 1.5 1.5 0 010 3z"/><path fill-rule="evenodd" d="M16.04 13.25a8 8 0 10-1.09 1.04c.4-.31.76-.66 1.09-1.04zm-1.1-1.04a7.97 7.97 0 00-9.89 0 6.5 6.5 0 119.9 0zm-1.1 1.04a6.47 6.47 0 01-7.67 0 6.47 6.47 0 017.66 0z"/></svg>`
};
export const aiCircleWarning: {
  name: 'circle_warning';
  data: string;
} = {
  name: 'circle_warning',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 12a1 1 0 11-2 0 1 1 0 012 0zm-.25-2.75v-5a.75.75 0 00-1.5 0v5a.75.75 0 001.5 0z"/><path fill-rule="evenodd" d="M10 16a8 8 0 110-16 8 8 0 010 16zm0-1.5a6.5 6.5 0 100-13 6.5 6.5 0 000 13z"/></svg>`
};
export const aiCircleX: {
  name: 'circle_x';
  data: string;
} = {
  name: 'circle_x',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.77 10.83L10 9.06l-1.77 1.77a.75.75 0 11-1.06-1.06L8.94 8 7.17 6.23a.75.75 0 011.06-1.06L10 6.94l1.77-1.77a.75.75 0 111.06 1.06L11.06 8l1.77 1.77a.75.75 0 11-1.06 1.06z"/><path fill-rule="evenodd" d="M18 8A8 8 0 112 8a8 8 0 0116 0zm-1.5 0a6.5 6.5 0 10-13 0 6.5 6.5 0 0013 0z"/></svg>`
};
export const aiCity: {
  name: 'city';
  data: string;
} = {
  name: 'city',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M3.5 2.75A2.75 2.75 0 016.25 0h6.5a2.75 2.75 0 012.75 2.75v.75h1.75A2.75 2.75 0 0120 6.25V16h-1.5V6.25c0-.69-.56-1.25-1.25-1.25h-2C14.56 5 14 4.44 14 3.75v-1c0-.69-.56-1.25-1.25-1.25h-6.5C5.56 1.5 5 2.06 5 2.75v5C5 8.44 4.44 9 3.75 9h-1c-.69 0-1.25.56-1.25 1.25V16H0v-5.75A2.75 2.75 0 012.75 7.5h.75V2.75z"/><path d="M6.5 3.5v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1A.5.5 0 008 3H7a.5.5 0 00-.5.5zm4 1v-1c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5zm-4 3v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1A.5.5 0 008 7H7a.5.5 0 00-.5.5zm4 1v-1c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5zm4.5-1v1c0 .28.22.5.5.5h1a.5.5 0 00.5-.5v-1a.5.5 0 00-.5-.5h-1a.5.5 0 00-.5.5zm0 4c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v1a.5.5 0 01-.5.5h-1a.5.5 0 01-.5-.5v-1zM3 11v1c0 .28.22.5.5.5h1A.5.5 0 005 12v-1a.5.5 0 00-.5-.5h-1a.5.5 0 00-.5.5zm5.5 5v-3.5a1 1 0 011-1h1a1 1 0 011 1V16h-3z"/></svg>`
};
export const aiClock: {
  name: 'clock';
  data: string;
} = {
  name: 'clock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.25 8V3.75a.75.75 0 011.5 0v3.94l1.43 1.43a.75.75 0 11-1.06 1.06L9.53 8.6a.76.76 0 01-.03-.03.75.75 0 01-.25-.56z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const aiCmd: {
  name: 'cmd';
  data: string;
} = {
  name: 'cmd',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2 2c-.3.3-.3.77 0 1.06L6.94 8 2 12.94A.75.75 0 003.06 14l5.3-5.3a1 1 0 000-1.4L3.05 2A.75.75 0 002 2zm7.75 12a.75.75 0 010-1.5h8.5a.75.75 0 010 1.5h-8.5z"/></svg>`
};
export const aiCode: {
  name: 'code';
  data: string;
} = {
  name: 'code',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M8 15a.75.75 0 01-.52-.93l3.6-12.55a.75.75 0 011.44.4l-3.6 12.56A.75.75 0 018 15zm9.44-7L13.5 4.06A.75.75 0 1114.56 3l4.3 4.3a1 1 0 010 1.4l-4.3 4.3a.75.75 0 01-1.06-1.06L17.44 8zM6.5 3c.3.3.3.77 0 1.06L2.56 8l3.94 3.94A.75.75 0 015.44 13l-4.3-4.3a1 1 0 010-1.4L5.45 3c.3-.3.77-.3 1.06 0z"/></svg>`
};
export const aiCompress: {
  name: 'compress';
  data: string;
} = {
  name: 'compress',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12.25 0c.41 0 .75.34.75.75V4.5c0 .28.22.5.5.5h3.75a.75.75 0 010 1.5H13.5a2 2 0 01-2-2V.75c0-.41.34-.75.75-.75zM7 15.25a.75.75 0 001.5 0V11.5a2 2 0 00-2-2H2.75a.75.75 0 000 1.5H6.5c.28 0 .5.22.5.5v3.75zM17.25 11a.75.75 0 000-1.5H13.5a2 2 0 00-2 2v3.75a.75.75 0 001.5 0V11.5c0-.28.22-.5.5-.5h3.75zM2.75 5a.75.75 0 000 1.5H6.5a2 2 0 002-2V.75a.75.75 0 00-1.5 0V4.5a.5.5 0 01-.5.5H2.75z"/></svg>`
};
export const aiDashboard: {
  name: 'dashboard';
  data: string;
} = {
  name: 'dashboard',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M5.5 9a2.5 2.5 0 100-5 2.5 2.5 0 000 5zm0-1.5a1 1 0 110-2 1 1 0 010 2z"/><path d="M3.75 12h12.5a.75.75 0 000-1.5H3.75a.75.75 0 000 1.5zm11-6.5h-4.5a.75.75 0 010-1.5h4.5a.75.75 0 010 1.5zm-4.5 3.25h3.5a.75.75 0 000-1.5h-3.5a.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M2 1a2 2 0 00-2 2v10c0 1.1.9 2 2 2h16a2 2 0 002-2V3a2 2 0 00-2-2H2zm16 1.5c.28 0 .5.22.5.5v10a.5.5 0 01-.5.5H2a.5.5 0 01-.5-.5V3c0-.28.22-.5.5-.5h16z"/></svg>`
};
export const aiDesktop: {
  name: 'desktop';
  data: string;
} = {
  name: 'desktop',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M1 2c0-1.1.9-2 2-2h14a2 2 0 012 2v9a2 2 0 01-2 2h-4.57l.25 1.5h.07a.75.75 0 010 1.5h-5.5a.75.75 0 010-1.5h.07l.25-1.5H3a2 2 0 01-2-2V2zm2-.5a.5.5 0 00-.5.5v9c0 .28.22.5.5.5h14a.5.5 0 00.5-.5V2a.5.5 0 00-.5-.5H3zm8.16 13L10.9 13H9.09l-.25 1.5h2.32z"/></svg>`
};
export const aiDevices: {
  name: 'devices';
  data: string;
} = {
  name: 'devices',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16 2v.5h1.5V2a2 2 0 00-2-2h-12a2 2 0 00-2 2v7H3V2c0-.28.22-.5.5-.5h12c.28 0 .5.22.5.5zM.4 10H11v2H1.6A1.6 1.6 0 010 10.4c0-.22.18-.4.4-.4z"/><path fill-rule="evenodd" d="M20 5v10a1 1 0 01-1 1h-5.5a1 1 0 01-1-1V5a1 1 0 011-1H19a1 1 0 011 1zm-6 9.5h4.5v-9H14v9z"/></svg>`
};
export const aiDisc: {
  name: 'disc';
  data: string;
} = {
  name: 'disc',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.25 8a2.75 2.75 0 115.5 0 2.75 2.75 0 01-5.5 0zM10 6.75a1.25 1.25 0 100 2.5 1.25 1.25 0 000-2.5z"/><path d="M10 3.25c0-.41.34-.76.75-.7a5.5 5.5 0 014.7 4.7c.06.41-.29.75-.7.75s-.74-.34-.82-.75a4 4 0 00-3.18-3.18c-.41-.08-.75-.4-.75-.82z"/><path fill-rule="evenodd" d="M10 16a8 8 0 100-16 8 8 0 000 16zm0-1.5a6.5 6.5 0 110-13 6.5 6.5 0 010 13z"/></svg>`
};
export const aiEllipsisV: {
  name: 'ellipsis_v';
  data: string;
} = {
  name: 'ellipsis_v',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 11.5a1.5 1.5 0 110 3 1.5 1.5 0 010-3zm0-10a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM11.5 8a1.5 1.5 0 10-3 0 1.5 1.5 0 003 0z"/></svg>`
};
export const aiEllipsis: {
  name: 'ellipsis';
  data: string;
} = {
  name: 'ellipsis',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6.5 8a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zm10 0a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0zM10 9.5a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"/></svg>`
};
export const aiExpand: {
  name: 'expand';
  data: string;
} = {
  name: 'expand',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M2.75 9.5c.41 0 .75.34.75.75V14c0 .28.22.5.5.5h3.75a.75.75 0 010 1.5H4a2 2 0 01-2-2v-3.75c0-.41.34-.75.75-.75zM8.5.75c0 .41-.34.75-.75.75H4a.5.5 0 00-.5.5v3.75a.75.75 0 01-1.5 0V2c0-1.1.9-2 2-2h3.75c.41 0 .75.34.75.75zm8.75 5.75a.75.75 0 01-.75-.75V2a.5.5 0 00-.5-.5h-3.75a.75.75 0 010-1.5H16a2 2 0 012 2v3.75c0 .41-.34.75-.75.75zm-5.75 8.75c0-.41.34-.75.75-.75H16a.5.5 0 00.5-.5v-3.75a.75.75 0 011.5 0V14a2 2 0 01-2 2h-3.75a.75.75 0 01-.75-.75z"/></svg>`
};
export const aiEyeSlash: {
  name: 'eye_slash';
  data: string;
} = {
  name: 'eye_slash',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M17.06 4.12l-.96.96A8.5 8.5 0 0117.96 8a8.5 8.5 0 01-10.03 5.25l-1.2 1.2A9.99 9.99 0 0019.54 8a10 10 0 00-2.38-3.98l-.1.1zm-3.79-2.57l-1.2 1.2A8.52 8.52 0 002.04 8a8.5 8.5 0 001.86 2.92l-.96.96-.1.1A10 10 0 01.46 8a10 10 0 0112.81-6.45z"/><path d="M6 8c0 .26.02.5.07.75l1.57-1.57a2.5 2.5 0 011.54-1.54l1.57-1.57A4 4 0 006 8zm4 4c-.26 0-.5-.02-.75-.07l1.57-1.57a2.5 2.5 0 001.54-1.54l1.57-1.57A4 4 0 0110 12zm6-8.94A.75.75 0 1014.94 2L4 12.94A.75.75 0 005.06 14L16 3.06z"/></svg>`
};
export const aiEye: {
  name: 'eye';
  data: string;
} = {
  name: 'eye',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 8a1 1 0 11-2 0 1 1 0 012 0z"/><path fill-rule="evenodd" d="M10 12a4 4 0 100-8 4 4 0 000 8zm0-1.5a2.5 2.5 0 110-5 2.5 2.5 0 010 5z"/><path fill-rule="evenodd" d="M10 1a10 10 0 019.44 6.7c.07.2.07.4 0 .6a10 10 0 01-18.88 0 .9.9 0 010-.6A10 10 0 0110 1zm0 12.5a8.5 8.5 0 007.81-5.15c.1-.22.1-.48 0-.7a8.5 8.5 0 00-15.62 0c-.1.22-.1.48 0 .7A8.5 8.5 0 0010 13.5z"/></svg>`
};
export const aiFastBackward: {
  name: 'fast_backward';
  data: string;
} = {
  name: 'fast_backward',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M1.75 14.5c.41 0 .75-.34.75-.75V2.25a.75.75 0 00-1.5 0v11.5c0 .41.34.75.75.75z"/><path fill-rule="evenodd" d="M12.5 13.48a1 1 0 01-1.62.78L4.27 8.98a1.25 1.25 0 010-1.96l6.6-5.28a1 1 0 011.63.78v10.96zM11 3.56L5.45 8 11 12.44V3.56z"/><path d="M14 11.16l3.88 3.1a1 1 0 001.62-.78V2.52a1 1 0 00-1.62-.78L14 4.84v1.92l4-3.2v8.88l-4-3.2v1.92z"/></svg>`
};
export const aiFastForward: {
  name: 'fast_forward';
  data: string;
} = {
  name: 'fast_forward',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M18.25 1.5a.75.75 0 00-.75.75v11.5a.75.75 0 001.5 0V2.25a.75.75 0 00-.75-.75z"/><path fill-rule="evenodd" d="M7.5 2.52a1 1 0 011.62-.78l6.61 5.28c.63.5.63 1.46 0 1.96l-6.6 5.28a1 1 0 01-1.63-.78V2.52zM9 12.44L14.55 8 9 3.56v8.88z"/><path d="M6 4.84l-3.88-3.1a1 1 0 00-1.62.78v10.96a1 1 0 001.62.78L6 11.16V9.24l-4 3.2V3.56l4 3.2V4.84z"/></svg>`
};
export const aiFloppyDisc: {
  name: 'floppy_disc';
  data: string;
} = {
  name: 'floppy_disc',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3.5 2v12c0 .28.22.5.5.5h1v-5a1 1 0 011-1h8a1 1 0 011 1v5h1a.5.5 0 00.5-.5V5.83a.5.5 0 00-.15-.36l1.06-1.06A2 2 0 0118 5.83V14a2 2 0 01-2 2H4a2 2 0 01-2-2V2c0-1.1.9-2 2-2h8.17a2 2 0 011.42.59L17.4 4.4l-1.06 1.06-3.82-3.82a.5.5 0 00-.36-.15H12v3a1 1 0 01-1 1H6a1 1 0 01-1-1v-3H4a.5.5 0 00-.5.5zm10 12.5v-4a.5.5 0 00-.5-.5H7a.5.5 0 00-.5.5v4h7zm-7-13v2c0 .28.22.5.5.5h3a.5.5 0 00.5-.5v-2h-4z"/></svg>`
};
export const aiFoldable: {
  name: 'foldable';
  data: string;
} = {
  name: 'foldable',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 15.99l-5.48-1.3A1 1 0 013 13.7V1.21A1 1 0 014.19.23L10 1.35 15.81.23a1 1 0 011.19.98v12.5a1 1 0 01-.77.97L10.75 16h-1.5zm0-1.54V2.74L4.5 1.82v11.5l4.75 1.13zm1.5 0l4.75-1.13V1.82l-4.75.92v11.7z"/></svg>`
};
export const aiForward: {
  name: 'forward';
  data: string;
} = {
  name: 'forward',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.37 1.72a1 1 0 00-1.62.78v10.96a1 1 0 001.62.78l6.61-5.28c.63-.5.63-1.45 0-1.95l-6.6-5.29zm5.43 6.26l-5.55 4.44V3.54l5.55 4.44z"/><path d="M4.37 1.72l3.88 3.1v1.92l-4-3.2v8.88l4-3.2v1.92l-3.88 3.1a1 1 0 01-1.62-.78V2.5a1 1 0 011.62-.78z"/></svg>`
};
export const aiGamepad: {
  name: 'gamepad';
  data: string;
} = {
  name: 'gamepad',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M4.75 6h.75v-.75a.75.75 0 011.5 0V6h.75a.75.75 0 010 1.5H7v.75a.75.75 0 01-1.5 0V7.5h-.75a.75.75 0 010-1.5zM13 7a1 1 0 100-2 1 1 0 000 2zm3 1a1 1 0 11-2 0 1 1 0 012 0z"/><path fill-rule="evenodd" d="M19.04 5.54l.72 4.08a4 4 0 01-7.37 3.1c-.2-.4-.58-.72-1.04-.72h-2.7c-.46 0-.84.32-1.04.73a4 4 0 01-7.37-3.1l.72-4.09A4.87 4.87 0 014.48 1.7 19.5 19.5 0 019.61 1h.78c1.73 0 3.46.23 5.13.69 1.82.5 3.19 2 3.52 3.85zm-.74 4.48l-.74-4.22a3.37 3.37 0 00-2.44-2.67 18 18 0 00-4.73-.63H9.6a18 18 0 00-4.73.63A3.37 3.37 0 002.44 5.8l-.74 4.22-.05.12A2.5 2.5 0 004 13.5a2.5 2.5 0 002.42-1.87 1.5 1.5 0 011.45-1.13h4.26c.68 0 1.28.46 1.45 1.13a2.5 2.5 0 104.77-1.49l-.05-.12z"/></svg>`
};
export const aiGear: {
  name: 'gear';
  data: string;
} = {
  name: 'gear',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10 11a3 3 0 100-6 3 3 0 000 6zm0-1.5a1.5 1.5 0 110-3 1.5 1.5 0 010 3z"/><path fill-rule="evenodd" d="M6.04 2.83L5.3 2.4a.93.93 0 00-1.15.14c-.38.41-.72.86-1 1.34L3 4.13c-.27.48-.49 1-.65 1.53-.13.42.07.85.45 1.07l.76.43a6.46 6.46 0 000 1.68l-.76.43a.92.92 0 00-.45 1.07c.16.53.38 1.05.65 1.53l.14.25c.3.48.63.93 1.01 1.34.3.31.77.36 1.15.14l.76-.43c.44.34.93.62 1.44.83v.88c0 .43.28.82.7.92a8.02 8.02 0 003.6 0c.43-.1.7-.49.7-.92V14a6.5 6.5 0 001.45-.83l.76.43c.37.22.85.17 1.14-.14.38-.41.72-.86 1.01-1.34l.15-.25c.26-.49.48-1 .65-1.53a.92.92 0 00-.45-1.07l-.76-.43c.07-.55.07-1.11 0-1.68l.76-.43a.92.92 0 00.45-1.07A7.96 7.96 0 0017 4.13l-.15-.25a8.03 8.03 0 00-1-1.34.93.93 0 00-1.15-.14l-.76.43A6.53 6.53 0 0012.49 2v-.88a.92.92 0 00-.7-.92 8.02 8.02 0 00-3.6 0c-.42.1-.7.49-.7.92V2a6.5 6.5 0 00-1.45.83zm3.38-1.3l.57-.03c.2 0 .39 0 .58.02.24.03.42.24.42.49v.66c0 .2.12.38.31.46l.62.25c.4.17.77.39 1.11.65l.53.4a.5.5 0 00.55.04l.57-.33a.47.47 0 01.63.12l.25.38.13.23.2.39c.1.22 0 .48-.2.6l-.58.34a.5.5 0 00-.24.5l.08.66c.06.43.06.86 0 1.28l-.08.66c-.03.2.07.4.24.5l.58.33c.2.13.3.39.2.61l-.2.39-.13.23-.25.38a.47.47 0 01-.63.12l-.57-.33a.5.5 0 00-.55.04l-.53.4a5 5 0 01-1.11.65l-.62.25a.5.5 0 00-.3.46V14a.5.5 0 01-.43.49 6.6 6.6 0 01-1.15 0 .47.47 0 01-.43-.49v-.66a.5.5 0 00-.3-.46l-.62-.25c-.4-.17-.77-.39-1.11-.65l-.53-.4a.5.5 0 00-.56-.04l-.57.33a.47.47 0 01-.63-.12 6.5 6.5 0 01-.24-.38l-.14-.23a6.5 6.5 0 01-.2-.39.47.47 0 01.21-.6l.57-.34a.5.5 0 00.25-.5l-.09-.66a4.96 4.96 0 010-1.28l.09-.66a.5.5 0 00-.25-.5l-.57-.33a.47.47 0 01-.2-.61c.06-.13.12-.26.2-.39l.13-.23c.07-.13.16-.25.24-.38.14-.2.42-.25.63-.12l.57.33c.18.1.4.08.56-.04l.52-.4a5 5 0 011.12-.65l.61-.25A.5.5 0 009 2.67V2c0-.25.18-.46.43-.49z"/></svg>`
};
export const aiGitHub: {
  name: 'git_hub';
  data: string;
} = {
  name: 'git_hub',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7.35 12.56c0 .07-.07.12-.17.12S7 12.64 7 12.56c0-.06.08-.11.17-.11.1-.01.18.04.18.11zm-1-.14c-.02.06.04.13.14.15.08.04.18 0 .2-.06.02-.06-.04-.14-.14-.17-.09-.02-.18.01-.2.08zm1.42-.06c-.09.02-.15.09-.14.16 0 .06.09.1.19.08.09-.02.15-.08.14-.15 0-.06-.1-.1-.19-.09zM9.9 0C5.42 0 2 3.4 2 7.87a8.09 8.09 0 005.47 7.72c.41.07.56-.18.56-.4l-.01-1.97s-2.26.48-2.74-.97c0 0-.36-.93-.9-1.18 0 0-.73-.5.06-.5 0 0 .8.07 1.24.84.71 1.24 1.9.89 2.36.67.07-.51.28-.87.51-1.08-1.8-.2-3.62-.46-3.62-3.57 0-.88.24-1.33.76-1.9a3.05 3.05 0 01.08-2.19c.68-.2 2.23.87 2.23.87a7.58 7.58 0 014.05 0s1.55-1.08 2.23-.87c.44 1.12.17 1.98.08 2.2.52.56.83 1 .83 1.9 0 3.1-1.9 3.35-3.7 3.56.3.25.55.74.55 1.5l-.01 2.69c0 .21.15.46.56.4A8.01 8.01 0 0018 7.86C18 3.4 14.37 0 9.9 0zM5.14 11.13c-.05.03-.04.1.02.16.05.06.12.08.17.04.04-.04.03-.11-.03-.17-.05-.05-.12-.08-.16-.03zm-.35-.27c-.03.05 0 .1.07.13.05.03.12.02.14-.02.02-.04-.01-.1-.07-.13-.07-.02-.12 0-.14.02zm1.04 1.15c-.05.04-.03.14.04.2.08.08.17.09.21.04.05-.05.03-.14-.04-.2-.07-.08-.17-.09-.2-.04zm-.37-.47c-.05.03-.05.11 0 .19.06.07.14.1.19.07.05-.04.05-.12 0-.2-.05-.07-.13-.1-.19-.06z"/></svg>`
};
export const aiHistory: {
  name: 'history';
  data: string;
} = {
  name: 'history',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M6.32 12.74a.84.84 0 00-1.1.03.7.7 0 00.03 1.04A7.5 7.5 0 104 3.5V1.74a.75.75 0 00-1.5 0V6a1 1 0 001 1h3.25a.75.75 0 000-1.5h-2.2a6 6 0 111.77 7.24z"/><path d="M9.25 8V3.75a.75.75 0 011.5 0v3.94l1.43 1.43a.75.75 0 11-1.06 1.06L9.53 8.6a.76.76 0 01-.03-.03.75.75 0 01-.25-.56z"/></svg>`
};
export const aiHolographic: {
  name: 'holographic';
  data: string;
} = {
  name: 'holographic',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M8.04 6.75h.01l.96 1.14-.01.02c-.18.14-.35.3-.53.48C7.9 8.94 7.3 9.5 6.5 9.5 4.01 9.5 2 7.36 2 4.72 2 1 3 1 6.5 1h7C17 1 18 2.06 18 4.72c0 2.64-2.01 4.78-4.5 4.78-.86 0-1.13-.25-1.6-.7l-.4-.36-.54-.48A1.5 1.5 0 009 7.89l-.96-1.15a3 3 0 013.92.11l.5.45c.19.15.34.3.45.4v.01a5.43 5.43 0 00.31.27c.03 0 .1.02.27.02 1.57 0 3-1.38 3-3.28 0-1.2-.24-1.57-.42-1.72-.25-.22-.9-.5-2.58-.5h-7c-.9 0-1.54 0-2.03.05-.5.05-.66.13-.7.16l-.02.03a.9.9 0 00-.1.24c-.09.32-.15.85-.15 1.74C3.5 6.62 4.93 8 6.5 8c.03 0 .1 0 .25-.1.19-.13.38-.3.69-.6l.01-.01c.17-.16.37-.36.59-.54zm5.18 1.22h.01z"/><path d="M5.42 11.8c-.45.16-.65.7-.34 1.06A6.41 6.41 0 0010 15c2.01 0 3.8-.82 4.88-2.1.32-.36.12-.9-.34-1.07-.33-.12-.7 0-.96.27A4.88 4.88 0 0110 13.5c-1.59 0-2.84-.6-3.61-1.43a.92.92 0 00-.97-.28zm6.08-7.3a.5.5 0 000-1h-3a.5.5 0 000 1h3z"/></svg>`
};
export const aiHome: {
  name: 'home';
  data: string;
} = {
  name: 'home',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.5 7.33V14c0 .28.22.5.5.5h10a.5.5 0 00.5-.5V7.33a.5.5 0 00-.15-.36l-5-5a.5.5 0 00-.7 0l-5 5a.5.5 0 00-.15.36zM3 14V7.33a2 2 0 01.59-1.42l5-5a2 2 0 012.82 0l5 5A2 2 0 0117 7.33V14a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>`
};
export const aiHourglassEmpty: {
  name: 'hourglass_empty';
  data: string;
} = {
  name: 'hourglass_empty',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14 1.5H6a.5.5 0 00-.5.5v.17a3.5 3.5 0 001.7 3l.79.47a2.75 2.75 0 010 4.72l-.8.47a3.5 3.5 0 00-1.69 3V14c0 .28.22.5.5.5h8a.5.5 0 00.5-.5v-.17a3.5 3.5 0 00-1.7-3l-.79-.47a2.75 2.75 0 010-4.72l.8-.47a3.5 3.5 0 001.69-3V2a.5.5 0 00-.5-.5zM6 0h8a2 2 0 012 2v.17a5 5 0 01-2.43 4.29l-.78.47a1.25 1.25 0 000 2.14l.78.47a5 5 0 012.43 4.3V14a2 2 0 01-2 2H6a2 2 0 01-2-2v-.17a5 5 0 012.43-4.29l.78-.47c.81-.48.81-1.66 0-2.14l-.78-.47A5 5 0 014 2.16V2c0-1.1.9-2 2-2z"/></svg>`
};
export const aiHourglassEnd: {
  name: 'hourglass_end';
  data: string;
} = {
  name: 'hourglass_end',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6 16h8a2 2 0 002-2v-.17a5 5 0 00-2.43-4.29l-.78-.47a1.25 1.25 0 010-2.14l.78-.47A5 5 0 0016 2.16V2a2 2 0 00-2-2H6a2 2 0 00-2 2v.17a5 5 0 002.43 4.29l.78.47c.81.48.81 1.66 0 2.14l-.78.47A5 5 0 004 13.84V14c0 1.1.9 2 2 2zm3.32-8c0-.91-.44-1.82-1.33-2.36l-.8-.47a3.5 3.5 0 01-1.69-3V2c0-.28.22-.5.5-.5h8c.28 0 .5.22.5.5v.17a3.5 3.5 0 01-1.7 3l-.79.47A2.73 2.73 0 0010.68 8H9.32z"/></svg>`
};
export const aiHourglassStart: {
  name: 'hourglass_start';
  data: string;
} = {
  name: 'hourglass_start',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14 0H6a2 2 0 00-2 2v.17a5 5 0 002.43 4.29l.78.47c.81.48.81 1.66 0 2.14l-.78.47A5 5 0 004 13.84V14c0 1.1.9 2 2 2h8a2 2 0 002-2v-.17a5 5 0 00-2.43-4.29l-.78-.47a1.25 1.25 0 010-2.14l.78-.47A5 5 0 0016 2.16V2a2 2 0 00-2-2zM9.32 8h1.36c0 .91.44 1.82 1.33 2.36l.8.47a3.5 3.5 0 011.69 3V14a.5.5 0 01-.5.5H6a.5.5 0 01-.5-.5v-.17a3.5 3.5 0 011.7-3l.79-.47A2.73 2.73 0 009.32 8z"/></svg>`
};
export const aiHourglass: {
  name: 'hourglass';
  data: string;
} = {
  name: 'hourglass',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M14 0H6a2 2 0 00-2 2v.17a5 5 0 002.43 4.29l.78.47c.81.48.81 1.66 0 2.14l-.78.47A5 5 0 004 13.84V14c0 1.1.9 2 2 2h8a2 2 0 002-2v-.17a5 5 0 00-2.43-4.29l-.78-.47a1.25 1.25 0 010-2.14l.78-.47A5 5 0 0016 2.16V2a2 2 0 00-2-2zM6 1.5h8c.28 0 .5.22.5.5v.17A3.5 3.5 0 0113.98 4H6.02a3.5 3.5 0 01-.52-1.83V2c0-.28.22-.5.5-.5zM9.32 8h1.36c0 .91.44 1.82 1.33 2.36l.8.47c.48.3.88.7 1.17 1.17H6.02c.29-.47.69-.88 1.18-1.17l.79-.47A2.73 2.73 0 009.32 8z"/></svg>`
};
export const aiLaptop: {
  name: 'laptop';
  data: string;
} = {
  name: 'laptop',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M1.5 11.5V3c0-1.1.9-2 2-2h13a2 2 0 012 2v8.5H17v-8a1 1 0 00-1-1H4a1 1 0 00-1 1v8H1.5zM18.21 15H1.8C.79 15 0 14.2 0 13.21c0-.39.32-.71.71-.71H19.3c.39 0 .71.32.71.71 0 .99-.8 1.79-1.79 1.79z"/></svg>`
};
export const aiLock: {
  name: 'lock';
  data: string;
} = {
  name: 'lock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 10.92a1 1 0 10-1.5 0V12a.75.75 0 001.5 0v-1.08z"/><path fill-rule="evenodd" d="M6 6H5a2 2 0 00-2 2v6c0 1.1.9 2 2 2h10a2 2 0 002-2V8a2 2 0 00-2-2h-1V4a4 4 0 00-8 0v2zm6.5-2v2h-5V4a2.5 2.5 0 015 0zm3 4v6a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V8c0-.28.22-.5.5-.5h10c.28 0 .5.22.5.5z"/></svg>`
};
export const aiMessagePen: {
  name: 'message_pen';
  data: string;
} = {
  name: 'message_pen',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M8.66 8.23l.11-.41a.25.25 0 00-.24-.32H4.25a.25.25 0 00-.25.25v1c0 .14.11.25.25.25h4.07c.16 0 .27-.14.27-.3 0-.15.02-.31.07-.47zM9.55 6c.07 0 .13-.03.18-.07l1-1a.25.25 0 00-.18-.43h-6.3a.25.25 0 00-.25.25v1c0 .14.11.25.25.25h5.3z"/><path d="M17.5 10V5.23l1.5-1.5V10a2 2 0 01-2 2h-6.88l-3.2 3.2a2 2 0 01-3.42-1.4V12H3a2 2 0 01-2-2V2c0-1.1.9-2 2-2h12.66l-1.5 1.5H3a.5.5 0 00-.5.5v8c0 .28.22.5.5.5h2v3.3c0 .44.54.66.85.35L9.5 10.5H17a.5.5 0 00.5-.5z"/><path d="M11.94 8.67L18.4 2.2c.1-.1.1-.25 0-.35L17.34.79a.25.25 0 00-.35 0l-6.48 6.47a.25.25 0 00-.06.11l-.35 1.26c-.05.17.1.34.28.31l1.42-.2c.05-.01.1-.04.14-.07z"/></svg>`
};
export const aiMessageText: {
  name: 'message_text';
  data: string;
} = {
  name: 'message_text',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M4 7.25v-1c0-.14.11-.25.25-.25h5.5c.14 0 .25.11.25.25v1c0 .14-.11.25-.25.25h-5.5A.25.25 0 014 7.25zm0-3v-1c0-.14.11-.25.25-.25h8.5c.14 0 .25.11.25.25v1c0 .14-.11.25-.25.25h-8.5A.25.25 0 014 4.25z"/><path fill-rule="evenodd" d="M10.12 12H17a2 2 0 002-2V2a2 2 0 00-2-2H3a2 2 0 00-2 2v8c0 1.1.9 2 2 2h.5v1.8a2 2 0 003.41 1.4l3.21-3.2zM17 1.5c.28 0 .5.22.5.5v8a.5.5 0 01-.5.5H9.5l-3.65 3.65a.5.5 0 01-.85-.36V10.5H3a.5.5 0 01-.5-.5V2c0-.28.22-.5.5-.5h14z"/></svg>`
};
export const aiMessage: {
  name: 'message';
  data: string;
} = {
  name: 'message',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10.12 12H17a2 2 0 002-2V2a2 2 0 00-2-2H3a2 2 0 00-2 2v8c0 1.1.9 2 2 2h.5v1.8a2 2 0 003.41 1.4l3.21-3.2zM17 1.5c.28 0 .5.22.5.5v8a.5.5 0 01-.5.5H9.5l-3.65 3.65a.5.5 0 01-.85-.36V10.5H3a.5.5 0 01-.5-.5V2c0-.28.22-.5.5-.5h14z"/></svg>`
};
export const aiMin: {
  name: 'min';
  data: string;
} = {
  name: 'min',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.75 8.75a.75.75 0 010-1.5h10.5a.75.75 0 010 1.5H4.75z"/></svg>`
};
export const aiNotes: {
  name: 'notes';
  data: string;
} = {
  name: 'notes',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12 1.5H4a.5.5 0 00-.5.5v8c0 .28.22.5.5.5h.5V12H4a2 2 0 01-2-2V2c0-1.1.9-2 2-2h8a2 2 0 012 2v.5h-1.5V2a.5.5 0 00-.5-.5z"/><path fill-rule="evenodd" d="M6 14V6c0-1.1.9-2 2-2h8a2 2 0 012 2v6.17a2 2 0 01-.59 1.42L15.6 15.4a2 2 0 01-1.42.59H8a2 2 0 01-2-2zm2-8.5a.5.5 0 00-.5.5v8c0 .28.22.5.5.5h6V13a1 1 0 011-1h1.5V6a.5.5 0 00-.5-.5H8z"/></svg>`
};
export const aiPaperPlane: {
  name: 'paper_plane';
  data: string;
} = {
  name: 'paper_plane',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M17.24 1.1a.5.5 0 00-.73-.54L2.34 8.53a.5.5 0 00.03.89l4.88 2.34v2.68a1 1 0 001.67.74l1.9-1.7 2.62 1.25a.5.5 0 00.7-.34l3.1-13.28zM9.36 12.78l-.61.55v-.84l.6.3zM4.75 8.9l9.35-5.25-6.45 6.65-2.9-1.4zm8.21 3.95l-3.89-1.87 5.7-5.88-1.8 7.75z"/></svg>`
};
export const aiPatreon: {
  name: 'patreon';
  data: string;
} = {
  name: 'patreon',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M18 6.09a5.75 5.75 0 11-11.5-.02A5.75 5.75 0 0118 6.1zM2 15.67h2.81V.33H2v15.34z"/></svg>`
};
export const aiPause: {
  name: 'pause';
  data: string;
} = {
  name: 'pause',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7 2.25v11.5a.75.75 0 01-1.5 0V2.25a.75.75 0 011.5 0zm6 0v11.5a.75.75 0 001.5 0V2.25a.75.75 0 00-1.5 0z"/></svg>`
};
export const aiPen: {
  name: 'pen';
  data: string;
} = {
  name: 'pen',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.43 14.57l9.66-9.66a2 2 0 000-2.82L15.9.9a2 2 0 00-2.82 0l-9.66 9.66a2 2 0 00-.55 1.02l-.73 3.67a.5.5 0 00.59.6l3.67-.74a2 2 0 001.02-.55zm5.63-11.5l1.88 1.87-8.57 8.57a.5.5 0 01-.26.14l-2.2.44.44-2.2a.5.5 0 01.14-.26l8.57-8.57z"/></svg>`
};
export const aiPhone: {
  name: 'phone';
  data: string;
} = {
  name: 'phone',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.82 11.09a6.5 6.5 0 01-2.9-2.91l1.33-.67a5 5 0 002.24 2.24l.19.09c.19.1.42.06.57-.1l.76-.75a1 1 0 011.12-.2l3.28 1.49a2 2 0 011.09 2.4l-.57 1.9A1.88 1.88 0 0115 15.93c-9.36-.72-12.55-8.26-12.97-13a1.8 1.8 0 011.33-1.85L5.33.5a2 2 0 012.4 1.09L9.2 4.87A1 1 0 019 5.99l-.76.76a.5.5 0 00-.09.57l.1.19-1.35.67-.09-.19a2 2 0 01.37-2.3l.51-.52-1.34-2.96a.5.5 0 00-.6-.27l-1.96.58c-.1.04-.18.1-.22.15a.17.17 0 00-.04.13 14 14 0 002.81 7.22c1.77 2.25 4.53 4.1 8.77 4.43.12 0 .3-.07.37-.3l.57-1.9a.5.5 0 00-.27-.6l-2.96-1.35-.51.5a2 2 0 01-2.31.38l-.19-.1z"/></svg>`
};
export const aiPlane: {
  name: 'plane';
  data: string;
} = {
  name: 'plane',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M4.48 9l-1 2.5H2.5v-7h.98l1 2.5h4.98l-1.5-5.5h1.22l3.5 5.5H15a2 2 0 011.06.3l.77.49c.16.1.16.32 0 .42l-.77.49A2 2 0 0115 9h-2.32l-3.5 5.5H7.96L9.46 9H4.48zM5.5 5.5l-.75-1.87A1 1 0 003.82 3H2a1 1 0 00-1 1v8a1 1 0 001 1h1.82a1 1 0 00.93-.63l.75-1.87h2l-1.16 4.24A1 1 0 007.31 16h2.14a1 1 0 00.84-.46l3.21-5.04h2.21a1 1 0 00.53-.15l2.4-1.5a1 1 0 000-1.7l-2.4-1.5a1 1 0 00-.53-.15H13.5L10.3.46A1 1 0 009.44 0H7.31a1 1 0 00-.97 1.26L7.5 5.5h-2z"/></svg>`
};
export const aiPlayPause: {
  name: 'play_pause';
  data: string;
} = {
  name: 'play_pause',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M12 2.25a.75.75 0 011.5 0v11.5a.75.75 0 01-1.5 0V2.25z"/><path fill-rule="evenodd" d="M1.75 2.52a1 1 0 011.62-.78l6.61 5.28c.63.5.63 1.46 0 1.96l-6.6 5.28a1 1 0 01-1.63-.78V2.52zM8.8 8L3.25 3.56v8.88L8.8 8z"/><path d="M17.25 1.5a.75.75 0 00-.75.75v11.5a.75.75 0 001.5 0V2.25a.75.75 0 00-.75-.75z"/></svg>`
};
export const aiPlay: {
  name: 'play';
  data: string;
} = {
  name: 'play',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.75 2.37v11.26L16.6 8 7.75 2.37zm-1.5-.46C6.25.92 7.34.33 8.17.86l9.57 6.09c.77.49.77 1.61 0 2.1l-9.57 6.1a1.25 1.25 0 01-1.92-1.06V1.9z"/></svg>`
};
export const aiPlus: {
  name: 'plus';
  data: string;
} = {
  name: 'plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.25 8.75v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5z"/></svg>`
};
export const aiPuzzle: {
  name: 'puzzle';
  data: string;
} = {
  name: 'puzzle',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13.33 4.27l.32-.96a1.21 1.21 0 10-2.3 0l.32.96a1.5 1.5 0 01-1.42 1.98h-2v1.72a1.52 1.52 0 01-2 1.44l-.94-.3a1.21 1.21 0 100 2.29l.94-.31c.98-.33 2 .4 2 1.44v1.97H16a.5.5 0 00.5-.5V6.25h-1.75a1.5 1.5 0 01-1.42-1.98zm-6.6 8.24l-.94.31a2.7 2.7 0 110-5.14l.93.31c.02 0 .03 0 .03-.02V5.25c0-.28.22-.5.5-.5h3l-.32-.96a2.72 2.72 0 115.14 0l-.32.96h2.75c.28 0 .5.22.5.5V14a2 2 0 01-2 2H7.25a.5.5 0 01-.5-.5v-2.97a.02.02 0 00-.03-.02z"/></svg>`
};
export const aiRefresh: {
  name: 'refresh';
  data: string;
} = {
  name: 'refresh',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M15.33 5.25a6 6 0 10-1.65 7.49.84.84 0 011.1.03.7.7 0 01-.03 1.04 7.5 7.5 0 111.75-9.55V1A.75.75 0 0118 1v4.75a1 1 0 01-1 1h-4.75a.75.75 0 010-1.5h3.08z"/></svg>`
};
export const aiRepeatOne: {
  name: 'repeat_one';
  data: string;
} = {
  name: 'repeat_one',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 .5c.3-.3.77-.3 1.06 0l3.82 3.82c.16.16.05.43-.17.43H6.75A3.25 3.25 0 003.5 8v.04c0 .48-.34.96-.82.96-.34 0-.63-.23-.66-.57a4.75 4.75 0 014.73-5.18h5.94L11 1.56A.75.75 0 0111 .5zM4.32 11.25a.25.25 0 00-.17.43l3.82 3.82a.75.75 0 101.06-1.06l-1.69-1.69h5.91a4.75 4.75 0 004.73-5.18c-.03-.34-.32-.57-.66-.57-.48 0-.83.48-.82.96V8c0 1.8-1.46 3.25-3.25 3.25H4.32z"/><path d="M9.75 9.5V7.56l-.16.18a.74.74 0 11-1.1-1.02l.63-.65a1.25 1.25 0 012.13.89V9.5a.75.75 0 01-1.5 0z"/></svg>`
};
export const aiRepeat: {
  name: 'repeat';
  data: string;
} = {
  name: 'repeat',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11 .5c.3-.3.77-.3 1.06 0l3.15 3.15c.2.2.2.5 0 .7L12.06 7.5A.75.75 0 1111 6.44l1.69-1.69H6.75A3.25 3.25 0 003.5 8v.04c0 .48-.34.96-.82.96-.34 0-.63-.23-.66-.57a4.75 4.75 0 014.73-5.18h5.94L11 1.56A.75.75 0 0111 .5z"/><path d="M9.03 15.5c-.3.3-.77.3-1.06 0l-3.15-3.15a.5.5 0 010-.7L7.97 8.5a.75.75 0 111.06 1.06l-1.69 1.69h5.91c1.8 0 3.25-1.46 3.25-3.25v-.04c0-.48.34-.96.82-.96.34 0 .63.23.66.57L18 8a4.75 4.75 0 01-4.75 4.75h-5.9l1.68 1.69c.3.3.3.77 0 1.06z"/></svg>`
};
export const aiRocket: {
  name: 'rocket';
  data: string;
} = {
  name: 'rocket',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14.5 5a1.5 1.5 0 11-3 0 1.5 1.5 0 013 0z"/><path fill-rule="evenodd" d="M8.5 3.5H5.13a2 2 0 00-1.96 1.6l-.44 2.2a1 1 0 00.98 1.2h2.46a.82.82 0 01.23.4l2.68 2.7c.12.1.26.18.41.22v2.84a1 1 0 001.29.95l2.28-.68A2 2 0 0014.5 13V9.5a8.1 8.1 0 003.2-7.65l-.14-.93a.58.58 0 00-.5-.5L16.14.3A8.1 8.1 0 008.5 3.5zm3.95 5.49L9.82 10.2 7.8 8.18l1.21-2.63a6.6 6.6 0 016.92-3.76l.24.04.04.24A6.6 6.6 0 0112.45 9zM6.69 7H4.33l.32-1.6a.5.5 0 01.49-.4h2.48l-.93 2zM13 10.38v2.63a.5.5 0 01-.36.48L11 14v-2.7l2-.93z"/><path fill-rule="evenodd" d="M7.27 10.73a2.5 2.5 0 010 3.54c-.98.97-3.8 2.2-4.77 1.23-.98-.98.26-3.8 1.23-4.77a2.5 2.5 0 013.54 0zM6.2 11.8a1 1 0 00-1.42 0 5.15 5.15 0 00-1.14 2.56A5.15 5.15 0 006.2 13.2a1 1 0 000-1.4z"/></svg>`
};
export const aiScreenWebcam: {
  name: 'screen_webcam';
  data: string;
} = {
  name: 'screen_webcam',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M10.75.75a.75.75 0 00-1.5 0v.75H3a2 2 0 00-2 2v8c0 1.1.9 2 2 2h14a2 2 0 002-2v-8a2 2 0 00-2-2h-6.25V.75zM17.5 3.5v8a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5v-8c0-.28.22-.5.5-.5h14c.28 0 .5.22.5.5z"/><path d="M16 15.25c0 .41-.34.75-.75.75H4.75a.75.75 0 010-1.5h10.5c.41 0 .75.34.75.75z"/></svg>`
};
export const aiServer: {
  name: 'server';
  data: string;
} = {
  name: 'server',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M15 3.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm-3.25.75a.75.75 0 100-1.5.75.75 0 000 1.5zm2.5 6a.75.75 0 100-1.5.75.75 0 000 1.5zm-1.75-.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0z"/><path fill-rule="evenodd" d="M2 2c0-1.1.9-2 2-2h12a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2V2zm2-.5a.5.5 0 00-.5.5v4h13V2a.5.5 0 00-.5-.5H4zm-.5 6V14c0 .28.22.5.5.5h12a.5.5 0 00.5-.5V7.5h-13z"/></svg>`
};
export const aiShieldKey: {
  name: 'shield_key';
  data: string;
} = {
  name: 'shield_key',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 8.3v1.45a.75.75 0 01-1.5 0V8.3a1.5 1.5 0 111.5 0z"/><path fill-rule="evenodd" d="M3.41 2.47L9.3.27a2 2 0 011.4 0l5.89 2.2a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03zm6.41-.8l-5.88 2.2c-.24.1-.3.28-.28.39.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0z"/></svg>`
};
export const aiShieldPlus: {
  name: 'shield_plus';
  data: string;
} = {
  name: 'shield_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.25 10.75v-2h-2a.75.75 0 010-1.5h2v-2a.75.75 0 011.5 0v2h2a.75.75 0 010 1.5h-2v2a.75.75 0 01-1.5 0z"/><path fill-rule="evenodd" d="M9.3.26L3.4 2.47A1.87 1.87 0 002.18 4.5C2.9 8.97 5.36 16 10 16c4.64 0 7.1-7.03 7.82-11.5.14-.89-.4-1.72-1.23-2.03L10.7.27a2 2 0 00-1.4 0zM3.94 3.88l5.88-2.21a.5.5 0 01.36 0l5.88 2.2c.24.1.3.28.28.39a22.44 22.44 0 01-2.27 6.94c-1.21 2.18-2.6 3.3-4.07 3.3-1.47 0-2.86-1.12-4.07-3.3a22.44 22.44 0 01-2.27-6.94c-.01-.11.04-.3.28-.38z"/></svg>`
};
export const aiShieldX: {
  name: 'shield_x';
  data: string;
} = {
  name: 'shield_x',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.41 10.47L10 9.07l-1.41 1.4a.75.75 0 11-1.06-1.06L8.93 8l-1.4-1.41a.75.75 0 011.06-1.06L10 6.93l1.41-1.4a.75.75 0 011.06 1.06L11.07 8l1.4 1.41a.75.75 0 11-1.06 1.06z"/><path fill-rule="evenodd" d="M9.3.26L3.4 2.47A1.87 1.87 0 002.18 4.5C2.9 8.97 5.36 16 10 16c4.64 0 7.1-7.03 7.82-11.5.14-.89-.4-1.72-1.23-2.03L10.7.27a2 2 0 00-1.4 0zM3.94 3.88l5.88-2.21a.5.5 0 01.36 0l5.88 2.2c.24.1.3.28.28.39a22.44 22.44 0 01-2.27 6.94c-1.21 2.18-2.6 3.3-4.07 3.3-1.47 0-2.86-1.12-4.07-3.3a22.44 22.44 0 01-2.27-6.94c-.01-.11.04-.3.28-.38z"/></svg>`
};
export const aiShield: {
  name: 'shield';
  data: string;
} = {
  name: 'shield',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M9.82 1.67l-5.88 2.2c-.24.1-.3.28-.28.39.34 2.12 1.1 4.82 2.27 6.94 1.21 2.18 2.6 3.3 4.07 3.3 1.47 0 2.86-1.12 4.07-3.3a22.44 22.44 0 002.27-6.94c.01-.11-.04-.3-.28-.38l-5.88-2.21a.5.5 0 00-.36 0zm-6.4.8L9.3.27a2 2 0 011.4 0l5.89 2.2a1.87 1.87 0 011.23 2.02C17.1 8.97 14.64 16 10 16 5.36 16 2.9 8.97 2.18 4.5c-.14-.89.4-1.72 1.23-2.03z"/></svg>`
};
export const aiShuffle: {
  name: 'shuffle';
  data: string;
} = {
  name: 'shuffle',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M14.81.5a.75.75 0 10-1.06 1.06l1.69 1.69H12.5c-.55 0-1.07.26-1.4.7L9.94 5.5l.94 1.25 1.42-1.9c.05-.06.12-.1.2-.1h2.94l-1.69 1.69a.75.75 0 001.06 1.06l3.15-3.15a.5.5 0 000-.7L14.8.5z"/><path d="M14.81 8.5a.75.75 0 10-1.06 1.06l1.69 1.69H12.5a.25.25 0 01-.2-.1l-5.4-7.2c-.33-.44-.85-.7-1.4-.7H2.75a.75.75 0 000 1.5H5.5c.08 0 .15.04.2.1l5.4 7.2c.33.44.85.7 1.4.7h2.94l-1.69 1.69a.75.75 0 001.06 1.06l3.15-3.15a.5.5 0 000-.7L14.8 8.5zM5.7 11.15l1.42-1.9.94 1.25-1.16 1.55c-.33.44-.85.7-1.4.7H2.75a.75.75 0 010-1.5H5.5c.08 0 .15-.04.2-.1z"/></svg>`
};
export const aiSimCard: {
  name: 'sim_card';
  data: string;
} = {
  name: 'sim_card',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 10h3V9a1 1 0 00-1-1h-2v2zm-3 2v-1h3v2H8a1 1 0 01-1-1zm6 0v-1h-2v2h1a1 1 0 001-1zM7 9v1h2V8H8a1 1 0 00-1 1z"/><path fill-rule="evenodd" d="M10.67 0a2 2 0 011.42.59L15.4 3.9a2 2 0 01.6 1.43V14a2 2 0 01-2 2H6a2 2 0 01-2-2V2c0-1.1.9-2 2-2h4.67zM5.5 14c0 .28.22.5.5.5h8a.5.5 0 00.5-.5V5.33a.5.5 0 00-.15-.36l-3.32-3.32a.5.5 0 00-.36-.15H6a.5.5 0 00-.5.5v12z"/></svg>`
};
export const aiSmartphone: {
  name: 'smartphone';
  data: string;
} = {
  name: 'smartphone',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 13.5a.75.75 0 100-1.5.75.75 0 000 1.5zm3-.75a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm-5.25.75a.75.75 0 100-1.5.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M4.5 2c0-1.1.9-2 2-2h7a2 2 0 012 2v12a2 2 0 01-2 2h-7a2 2 0 01-2-2V2zm2-.5A.5.5 0 006 2v12c0 .28.22.5.5.5h7a.5.5 0 00.5-.5V2a.5.5 0 00-.5-.5h-7z"/></svg>`
};
export const aiSoftwareBox: {
  name: 'software_box';
  data: string;
} = {
  name: 'software_box',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M5 2.5L6.2.49A1 1 0 017.08 0h10.05a.5.5 0 01.43.76L16.5 2.5H5zM3 5H1.54a.5.5 0 01-.39-.81L2.2 2.88a1 1 0 01.78-.38H5L3 5zm11 0H3v9c0 1.1.9 2 2 2h3.26a5.5 5.5 0 01-.89-1.5H5.5a1 1 0 01-1-1v-7h8V7c1.1 0 2.14.33 3 .89V5h.59a1 1 0 00.7-.3l1.36-1.35a.5.5 0 00-.36-.85H16.5L14 5z"/><path d="M12.25 13a.75.75 0 100-1.5.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M16 12.25a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/></svg>`
};
export const aiSpinnerThird: {
  name: 'spinner_third';
  data: string;
} = {
  name: 'spinner_third',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10 .75a.7.7 0 01.75-.72 8 8 0 016.52 11.3.7.7 0 01-1 .3.83.83 0 01-.3-1.05 6.5 6.5 0 00-5.22-9.04c-.41-.05-.75-.38-.75-.8z"/></svg>`
};
export const aiStop: {
  name: 'stop';
  data: string;
} = {
  name: 'stop',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M5 3h10v10H5V3zm-.5-1.5a1 1 0 00-1 1v11a1 1 0 001 1h11a1 1 0 001-1v-11a1 1 0 00-1-1h-11z"/></svg>`
};
export const aiStopwatch: {
  name: 'stopwatch';
  data: string;
} = {
  name: 'stopwatch',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M9.25 9.5V6.75a.75.75 0 011.5 0v2.44l.91.91a.75.75 0 01-1.06 1.06L9.53 10.1a.78.78 0 01-.03-.03.75.75 0 01-.25-.56z"/><path fill-rule="evenodd" d="M14.24 4.57a6.47 6.47 0 00-3.49-1.53V1.5h1.75a.75.75 0 000-1.5h-5a.75.75 0 000 1.5h1.75v1.54a6.5 6.5 0 106 2.63l1.2-1.11a.75.75 0 00-1.01-1.1l-1.2 1.1zM10 14.5a5 5 0 110-10 5 5 0 010 10z"/></svg>`
};
export const aiStore: {
  name: 'store';
  data: string;
} = {
  name: 'store',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M4.35 3.64c.42-.16.88-.16 1.3 0l1.66.67a.5.5 0 00.38 0l1.66-.67.56 1.4-1.67.66a2 2 0 01-1.48 0l-1.67-.66a.25.25 0 00-.18 0l-1.67.66a2 2 0 01-.24.08V16H1.5V5.6l-.65-.26a1 1 0 01-.59-1.22L1.5 0h17l1.24 4.12a1 1 0 01-.59 1.22l-.65.26V16H17V8.5h-3.75a.25.25 0 00-.25.25V16h-1.5V8.75c0-.97.78-1.75 1.75-1.75H17V5.78a2 2 0 01-.24-.08l-1.67-.66.56-1.4 1.66.67a.5.5 0 00.38 0l.48-.2-.79-2.61H2.62l-.79 2.62.48.19a.5.5 0 00.38 0l1.66-.67z"/><path d="M14.9 5.04l-.55-1.4c.42-.16.88-.16 1.3 0l-.56 1.4a.25.25 0 00-.18 0z"/><path d="M10.1 5.04l.55-1.4 1.66.67a.5.5 0 00.38 0l1.66-.67.56 1.4-1.67.66a2 2 0 01-1.48 0l-1.67-.66z"/><path d="M10.1 5.04l.55-1.4a1.75 1.75 0 00-1.3 0l.56 1.4a.25.25 0 01.18 0z"/><path fill-rule="evenodd" d="M4.5 9c0-1.1.9-2 2-2H8a2 2 0 012 2v2a2 2 0 01-2 2H6.5a2 2 0 01-2-2V9zm2-.5A.5.5 0 006 9v2c0 .28.22.5.5.5H8a.5.5 0 00.5-.5V9a.5.5 0 00-.5-.5H6.5z"/></svg>`
};
export const aiTrashCan: {
  name: 'trash_can';
  data: string;
} = {
  name: 'trash_can',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M7.5 12.5v-6c0-.28.22-.5.5-.5h.5c.28 0 .5.22.5.5v6a.5.5 0 01-.5.5H8a.5.5 0 01-.5-.5zm3.5-6v6c0 .28.22.5.5.5h.5a.5.5 0 00.5-.5v-6A.5.5 0 0012 6h-.5a.5.5 0 00-.5.5z"/><path fill-rule="evenodd" d="M6.5 3l.22-1.33A2 2 0 018.7 0h2.62a2 2 0 011.97 1.67L13.5 3h2.75a.75.75 0 010 1.5H16l-.84 9.67a2 2 0 01-2 1.83H6.84a2 2 0 01-1.99-1.83L4 4.5h-.25a.75.75 0 010-1.5H6.5zM8 3h4l-.39-1.16a.5.5 0 00-.47-.34H8.86a.5.5 0 00-.47.34L8 3zm5.66 11.04l.83-9.54H5.51l.83 9.54a.5.5 0 00.5.46h6.33a.5.5 0 00.5-.46z"/></svg>`
};
export const aiTwitter: {
  name: 'twitter';
  data: string;
} = {
  name: 'twitter',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M16.36 4.74v.43c0 4.33-3.3 9.33-9.32 9.33A9.27 9.27 0 012 13.03a6.8 6.8 0 004.86-1.37A3.28 3.28 0 013.8 9.4a3.47 3.47 0 001.48-.06 3.28 3.28 0 01-2.63-3.22v-.04c.44.24.94.4 1.48.42a3.28 3.28 0 01-1.01-4.4 9.32 9.32 0 006.76 3.43 3.28 3.28 0 015.6-3 6.46 6.46 0 002.07-.78c-.24.76-.76 1.4-1.44 1.8.66-.07 1.3-.25 1.89-.5-.45.65-1 1.22-1.64 1.7z"/></svg>`
};
export const aiUnlock: {
  name: 'unlock';
  data: string;
} = {
  name: 'unlock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M10.75 10.92a1 1 0 10-1.5 0V12a.75.75 0 001.5 0v-1.08z"/><path fill-rule="evenodd" d="M12.5 4v2H5a2 2 0 00-2 2v6c0 1.1.9 2 2 2h10a2 2 0 002-2V8a2 2 0 00-2-2h-1V4a4 4 0 00-8 0v.5h1.5V4a2.5 2.5 0 015 0zm3 4v6a.5.5 0 01-.5.5H5a.5.5 0 01-.5-.5V8c0-.28.22-.5.5-.5h10c.28 0 .5.22.5.5z"/></svg>`
};
export const aiUserLock: {
  name: 'user_lock';
  data: string;
} = {
  name: 'user_lock',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.36 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M1.77 13.47c-.81-.87-1.08-2.22-.32-3.14a3.64 3.64 0 012.3-1.28c1.66-.24 3.35-.32 5.03-.25-.35.43-.6.93-.7 1.48-1.38-.02-2.76.06-4.13.26-.54.08-1.01.35-1.34.75-.08.1-.13.22-.1.43.03.23.15.5.36.72a6.48 6.48 0 005.16 2.05c.08.53.27 1.02.56 1.45a8.08 8.08 0 01-6.82-2.47zm12.73-.22a.75.75 0 100-1.5.75.75 0 000 1.5z"/><path fill-rule="evenodd" d="M10 11c0-1.1.9-2 2-2v-.5a2.5 2.5 0 015 0V9a2 2 0 012 2v3a2 2 0 01-2 2h-5a2 2 0 01-2-2v-3zm7-.5h-5a.5.5 0 00-.5.5v3c0 .28.22.5.5.5h5a.5.5 0 00.5-.5v-3a.5.5 0 00-.5-.5zm-1.5-2a1 1 0 10-2 0V9h2v-.5z"/></svg>`
};
export const aiUserPlus: {
  name: 'user_plus';
  data: string;
} = {
  name: 'user_plus',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M11.36 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0z"/><path d="M1.77 13.47c-.81-.87-1.08-2.22-.32-3.14a3.64 3.64 0 012.3-1.28c2.43-.35 4.9-.36 7.34-.05h-.84c-.9 0-1.67.53-2.03 1.28-1.43-.03-2.85.06-4.27.26-.54.08-1.01.35-1.34.75-.08.1-.13.22-.1.43.03.23.15.5.36.72a6.48 6.48 0 008.2 1.06H12v1.19a7.96 7.96 0 01-10.23-1.22z"/><path d="M15 7.25v3.25h3.25a.75.75 0 010 1.5H15v3.25a.75.75 0 01-1.5 0V12h-3.25a.75.75 0 010-1.5h3.25V7.25a.75.75 0 011.5 0z"/></svg>`
};
export const aiUser: {
  name: 'user';
  data: string;
} = {
  name: 'user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M13.75 3.75a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zm-1.5 0a2.25 2.25 0 10-4.5 0 2.25 2.25 0 004.5 0zm-8.09 9.72c-.81-.87-1.08-2.22-.32-3.14a3.64 3.64 0 012.3-1.28 27.8 27.8 0 017.73 0c.92.13 1.73.6 2.29 1.28.76.92.5 2.27-.32 3.14a7.98 7.98 0 01-11.68 0zM5 11.29c-.08.1-.13.22-.1.43.03.23.15.5.36.72a6.48 6.48 0 009.48 0c.21-.22.33-.49.36-.72.03-.2-.02-.34-.1-.43-.33-.4-.8-.67-1.34-.75a25.85 25.85 0 00-7.32 0c-.54.08-1.01.35-1.34.75z"/></svg>`
};
export const aiVolume0: {
  name: 'volume_0';
  data: string;
} = {
  name: 'volume_0',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7 10.5v-5h2.15c.57 0 1.12-.2 1.56-.55L13 3.12v9.76l-2.29-1.83a2.5 2.5 0 00-1.56-.55H7zm2.77-6.72a1 1 0 01-.62.22H6.5a1 1 0 00-1 1v6a1 1 0 001 1h2.65a1 1 0 01.62.22l3.92 3.13a.5.5 0 00.81-.39V1.04a.5.5 0 00-.81-.39L9.77 3.78z"/></svg>`
};
export const aiVolume1: {
  name: 'volume_1';
  data: string;
} = {
  name: 'volume_1',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M7.77 3.78L11.7.65a.5.5 0 01.81.39v13.92a.5.5 0 01-.81.39l-3.92-3.13a1 1 0 00-.62-.22H4.5a1 1 0 01-1-1V5a1 1 0 011-1h2.65a1 1 0 00.62-.22zm-.62 6.72c.57 0 1.12.2 1.56.55L11 12.88V3.12L8.71 4.95c-.44.36-1 .55-1.56.55H5v5h2.15z"/><path d="M16.5 8a2.5 2.5 0 01-2.5 2.5V9a1 1 0 100-2V5.5A2.5 2.5 0 0116.5 8z"/></svg>`
};
export const aiVolume2: {
  name: 'volume_2';
  data: string;
} = {
  name: 'volume_2',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M6.77 3.78L10.7.65a.5.5 0 01.81.39v13.92a.5.5 0 01-.81.39l-3.92-3.13a1 1 0 00-.62-.22H3.5a1 1 0 01-1-1V5a1 1 0 011-1h2.65a1 1 0 00.62-.22zm-.62 6.72c.57 0 1.12.2 1.56.55L10 12.88V3.12L7.71 4.95c-.44.36-1 .55-1.56.55H4v5h2.15z"/><path d="M18 8a5 5 0 01-5 5v-1.5a3.5 3.5 0 100-7V3a5 5 0 015 5z"/><path d="M15.5 8a2.5 2.5 0 01-2.5 2.5V9a1 1 0 100-2V5.5A2.5 2.5 0 0115.5 8z"/></svg>`
};
export const aiVolume3: {
  name: 'volume_3';
  data: string;
} = {
  name: 'volume_3',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M11.5 15.5h-.07c.05-.17.07-.35.07-.54V14a6 6 0 000-12v-.96c0-.19-.02-.37-.07-.54h.07a7.5 7.5 0 010 15z"/><path d="M16.5 8a5 5 0 01-5 5v-1.5a3.5 3.5 0 100-7V3a5 5 0 015 5z"/><path d="M14 8a2.5 2.5 0 01-2.5 2.5V9a1 1 0 100-2V5.5A2.5 2.5 0 0114 8z"/><path fill-rule="evenodd" d="M5.27 3.78L9.2.65a.5.5 0 01.81.39v13.92a.5.5 0 01-.81.39l-3.92-3.13a1 1 0 00-.62-.22H2a1 1 0 01-1-1V5a1 1 0 011-1h2.65a1 1 0 00.62-.22zm-.62 6.72c.57 0 1.12.2 1.56.55l2.29 1.83V3.12L6.21 4.95c-.44.36-1 .55-1.56.55H2.5v5h2.15z"/></svg>`
};
export const aiVolumeNone: {
  name: 'volume_none';
  data: string;
} = {
  name: 'volume_none',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path d="M13.69.65a.5.5 0 01.59-.03c-.15.1-.28.2-.4.32L9.32 5.49l-.17.01H7v2.32l-1.5 1.5V5a1 1 0 011-1h2.65a1 1 0 00.62-.22L13.7.65zM9.18 12l1.19-1.18c.12.06.23.14.34.23L13 12.88v-4.7l1.5-1.5v8.28a.5.5 0 01-.81.39l-3.92-3.13a1 1 0 00-.59-.22zM16 3.06A.75.75 0 0014.94 2L4 12.94A.75.75 0 005.06 14L16 3.06z"/></svg>`
};
export const aiWindow: {
  name: 'window';
  data: string;
} = {
  name: 'window',
  data: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16"><path fill-rule="evenodd" d="M3 0a2 2 0 00-2 2v12c0 1.1.9 2 2 2h14a2 2 0 002-2V2a2 2 0 00-2-2H3zm-.5 14V3.5h15V14a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5zm10-12.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm1.75.75a.75.75 0 110-1.5.75.75 0 010 1.5zm2.5 0a.75.75 0 110-1.5.75.75 0 010 1.5z"/></svg>`
};
export type Amaranth =
  | 'alarm'
  | 'angle_down'
  | 'angle_left'
  | 'angle_right'
  | 'angle_up'
  | 'arrow_down_to_line'
  | 'arrow_down'
  | 'arrow_left_from_bracket'
  | 'arrow_left_to_bracket'
  | 'arrow_left_to_line'
  | 'arrow_left'
  | 'arrow_right_from_bracket'
  | 'arrow_right_to_bracket'
  | 'arrow_right_to_line'
  | 'arrow_right'
  | 'arrow_up_to_line'
  | 'arrow_up'
  | 'azure'
  | 'backward'
  | 'bars_staggered'
  | 'bars'
  | 'bel'
  | 'box'
  | 'branch_up'
  | 'branch'
  | 'building'
  | 'calendar_agenda'
  | 'calendar_day'
  | 'calendar_holidays'
  | 'calendar_month'
  | 'calendar_week'
  | 'calendar'
  | 'change_windows_can'
  | 'change_windows_dev'
  | 'change_windows'
  | 'check'
  | 'chip'
  | 'circle_check'
  | 'circle_info'
  | 'circle_plus'
  | 'circle_user'
  | 'circle_warning'
  | 'circle_x'
  | 'city'
  | 'clock'
  | 'cmd'
  | 'code'
  | 'compress'
  | 'dashboard'
  | 'desktop'
  | 'devices'
  | 'disc'
  | 'ellipsis_v'
  | 'ellipsis'
  | 'expand'
  | 'eye_slash'
  | 'eye'
  | 'fast_backward'
  | 'fast_forward'
  | 'floppy_disc'
  | 'foldable'
  | 'forward'
  | 'gamepad'
  | 'gear'
  | 'git_hub'
  | 'history'
  | 'holographic'
  | 'home'
  | 'hourglass_empty'
  | 'hourglass_end'
  | 'hourglass_start'
  | 'hourglass'
  | 'laptop'
  | 'lock'
  | 'message_pen'
  | 'message_text'
  | 'message'
  | 'min'
  | 'notes'
  | 'paper_plane'
  | 'patreon'
  | 'pause'
  | 'pen'
  | 'phone'
  | 'plane'
  | 'play_pause'
  | 'play'
  | 'plus'
  | 'puzzle'
  | 'refresh'
  | 'repeat_one'
  | 'repeat'
  | 'rocket'
  | 'screen_webcam'
  | 'server'
  | 'shield_key'
  | 'shield_plus'
  | 'shield_x'
  | 'shield'
  | 'shuffle'
  | 'sim_card'
  | 'smartphone'
  | 'software_box'
  | 'spinner_third'
  | 'stop'
  | 'stopwatch'
  | 'store'
  | 'trash_can'
  | 'twitter'
  | 'unlock'
  | 'user_lock'
  | 'user_plus'
  | 'user'
  | 'volume_0'
  | 'volume_1'
  | 'volume_2'
  | 'volume_3'
  | 'volume_none'
  | 'window';
export interface IconDefinition {
  name: Amaranth;
  data: string;
}
export type IconDefinitionNameSubset<
  T extends Readonly<IconDefinition[]>
> = T[number]['name'];
